print("What is your name?")
a=input("Enter Your Name")
print("My Name Is:",a)
print("Shuru Kor")
x=input("Enter your size:")
y=input("Enter your last date:")
print(x+y)
print(int(x)+int(y))
print("He said,\"I want to eat an apple\"")
